services:
  - type: web
    name: excel-protection-remover
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 